# Generated by Django 5.0.4 on 2024-04-10 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_rename_name_url_domain_name_remove_search_results_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='is_favorite',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_searches', to=settings.AUTH_USER_MODEL),
        ),
    ]
