# Generated by Django 5.0.4 on 2024-04-10 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0003_alter_search_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='search_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.search'),
        ),
        migrations.AlterField(
            model_name='url',
            name='search_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.search'),
        ),
    ]
